apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aria2-pro-ng.fullname" . }}
  labels:
    {{- include "aria2-pro-ng.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aria2-pro-ng.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aria2-pro-ng.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aria2-pro-ng.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: aria2pro
          env:
          - name: DISK_CACHE
            value: 64M
          - name: IPV6_MODE
            value: "false"
          - name: LISTEN_PORT
            value: "6888"
          - name: PGID
            value: "65534"
          - name: PUID
            value: "65534"
          - name: RPC_PORT
            value: "6800"
          - name: RPC_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "aria2-pro-ng.fullname" . }}
                key: rpcSecret
          - name: TZ
            value: Asia/Shanghai
          - name: UMASK_SET
            value: "022"
          - name: UPDATE_TRACKERS
            value: "true"
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.aria2pro.repository }}:{{ .Values.image.aria2pro.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.aria2pro.pullPolicy }}
          ports:
            - name: {{ .Values.service.aria2pro.name }}
              containerPort: 6800
              protocol: TCP
          {{- with .Values.livenessProbe.aria2pro }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.aria2pro | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe.aria2pro }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.aria2pro | nindent 12 }}
          {{- end }}
          {{- with .Values.resources.aria2pro }}
          resources:
            {{- toYaml .Values.resources.aria2pro | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts.aria2pro }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: ariang
          args:
          - --port
          - "6880"
          - --ipv6
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.ariang.repository }}:{{ .Values.image.ariang.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.ariang.pullPolicy }}
          ports:
            - name: {{ .Values.service.ariang.name }}
              containerPort: 6880
              protocol: TCP
          {{- with .Values.livenessProbe.ariang }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.ariang | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe.ariang }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.ariang | nindent 12 }}
          {{- end }}
          {{- with .Values.resources.ariang }}
          resources:
            {{- toYaml .Values.resources.ariang | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts.ariang }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
