apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aria2-pro-ng.fullname" . }}
  labels:
    {{- include "aria2-pro-ng.labels" . | nindent 4 }}
spec:
  type: Opaque
  data:  {{ include "aria2-pro-ng.rpcSecret" . | quote }}