apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aria2-pro-ng.fullname" . }}
  labels:
    {{- include "aria2-pro-ng.labels" . | nindent 4 }}
type: Opaque
data:
  rpcSecret: {{ include "aria2-pro-ng.rpcSecret" . | b64enc | quote }}